run:
  timeout: 5m
  go: "1.24"

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goprintffuncname
    - gosimple
    - govet
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - rowserrcheck
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - gosec
    - misspell
    - whitespace
    - exhaustive
    - copyloopvar
    - sqlclosecheck
    - wastedassign
    - ineffassign
    - mirror
    - nilnil
    - nosprintfhostport
    - dupl
    # TODO: add and fix issues
    #- revive
    #- noctx
    #- musttag
linters-settings:
  prealloc:
    # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them.
    # True by default.
    simple: true
    range-loops: true # Report preallocation suggestions on range loops, true by default
    for-loops: true # Report preallocation suggestions on for loops, false by default
  gocritic:
    # Enable multiple checks by tags, run `GL_DEBUG=gocritic golangci-lint run` to see all tags and checks.
    # Empty list by default. See https://github.com/go-critic/go-critic#usage -> section "Tags".
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - ifElseChain
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude-rules:
    - path: _test\.go # to exclude all test files for linter errcheck
      linters:
        - errcheck
        - goconst
    - linters:
        - gosec
      text: "G101:"
    - linters:
        - gosec
      text: "G404:"
    - linters:
        - gosec
      text: "G115:" # integer overflow conversion int -> uint16
