{
 "title": "go-libp2p Autonat",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "instance", "query": { "query": "label_values(up, instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Reachability Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "libp2p_autonat_reachability_status{instance=~\"$instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Reachability status confidence",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_autonat_reachability_status_confidence{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Next Probe Time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_autonat_next_probe_timestamp{instance=~\"$instance\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Dial Responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 7 },
   "targets": [
    {
     "expr": "increase(libp2p_autonat_received_dial_response_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{response_status}}"
    }
   ]
  },
  {
   "title": "Outgoing Dial Responses",
   "type": "timeseries",
   "description": "Responses sent to peers that are asking us to dial them",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(libp2p_autonat_outgoing_dial_response_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{response_status}}"
    }
   ]
  },
  {
   "title": "Outgoing Dial Refused",
   "type": "timeseries",
   "description": "There are multiple reasons why we'd refuse a dial-back request from a remote node:\n* rate limiting\n* no valid addresses\n* dial blocked by policy",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(libp2p_autonat_outgoing_dial_refused_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{refusal_reason}}"
    }
   ]
  }
 ]
}