apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Pyroscope
    orgId: 1

datasources:
  - name: Prometheus
    orgId: 1
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: false
  - name: Pyroscope
    orgId: 1
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://pyroscope:4040
    editable: false
