// Package sockmark provides per-platform mechanisms to mark sockets so that
// traffic generated by libp2p bypasses the AWL VPN tunnel when gateway mode
// is enabled.
//
// Platform implementations:
//   - Linux: SO_MARK + ip-rule policy routing.
//   - Android: VpnService.protect() callback supplied by the host app.
//   - Windows: IP_UNICAST_IF binding to the physical NIC (currently unused —
//     gateway mode is blocked on Windows in setupGateway, see windows file).
//   - Other platforms: no-op.
//
// The Application owns a single Marker instance (created via New) and feeds
// its ControlFunc to the libp2p host config. Replacing the previous global
// variables with a struct removes data races between SetProtector callers
// (Android JNI) and libp2p goroutines that read the control func at dial
// time.
package sockmark

import "syscall"

// Marker abstracts the platform-specific socket-marking implementation.
type Marker interface {
	// ControlFunc returns a function compatible with net.Dialer.Control and
	// the QUIC ListenUDP override. It returns nil when the platform is not
	// configured (e.g. Android before the host app supplies a protector).
	ControlFunc() func(network, address string, c syscall.RawConn) error

	// FWMark returns the firewall mark applied by this Marker on Linux. It
	// is consumed by vpn/routes when installing the matching ip-rule.
	// Returns 0 on platforms that do not use SO_MARK.
	FWMark() uint32
}
