name: golangci-lint
on: [ push, pull_request ]
jobs:
  golangci:
    name: lint
    # run job on all pushes OR external PR, not both
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Create stub embed files
        run: mkdir static && touch static/index.html && touch embeds/wintun.dll
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
